/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package codigo;

/**
 *
 * @author alexi
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAnalizar = new javax.swing.JButton();
        txtEntrada = new java.awt.TextArea();
        txtSalida = new java.awt.TextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAnalizar.setBackground(new java.awt.Color(102, 255, 102));
        btnAnalizar.setText("Analizar Código");
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(txtSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(btnAnalizar))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(txtSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(btnAnalizar)))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
                                                 
    // 1. EJECUCIÓN NORMAL DEL COMPILADOR
    AnalizadorLexico lexer = new AnalizadorLexico();
    String resultado = lexer.analizar(txtEntrada.getText());
    txtSalida.setText(resultado);

    // 2. GENERACIÓN DINÁMICA DE LA TABLA DE TOKENS
    javax.swing.table.DefaultTableModel modeloTabla =
            (javax.swing.table.DefaultTableModel) jTable1.getModel();

    // Limpiamos la tabla y colocamos los encabezados correctos
    modeloTabla.setRowCount(0);
    modeloTabla.setColumnIdentifiers(new String[]{
        "Token",
        "Lexema",
        "Expresión Regular",
        "Reservada"
    });

    String codigoFuente = txtEntrada.getText();
    String[] lineas = codigoFuente.split("\n");

    // Separador que respeta cadenas entre comillas
    java.util.regex.Pattern patronSeparador =
            java.util.regex.Pattern.compile("\"(?:[^\"\\\\]|\\\\.)*\"|\\S+");

    for (String linea : lineas) {
        linea = linea.trim();

        if (linea.isEmpty()) {
            continue;
        }

        java.util.regex.Matcher matcher = patronSeparador.matcher(linea);

        while (matcher.find()) {
            String palabra = matcher.group();

            // Token y lexema serán exactamente iguales
            String token = palabra;
            String lexema = palabra;

            String patron = "Desconocido";
            String reservada = "No";

            // Comentario: se agrega a la tabla y se corta la lectura de la línea
            if (palabra.equals("01")) {
                patron = "\\b01\\b";
                reservada = "Sí";

                modeloTabla.addRow(new Object[]{
                    token,
                    lexema,
                    patron,
                    reservada
                });

                break;
            }

            String clasificacionDiccionario = Diccionario.clasificarToken(palabra);

            if (!clasificacionDiccionario.equals("Desconocido")) {
                reservada = "Sí";

                if (palabra.equals("fin")) {
                    patron = "\\bfin$";
                } else {
                    patron = "\\b" + palabra + "\\b";
                }

            } else if (palabra.equals("verdadero") || palabra.equals("falso")) {
                patron = "\\b" + palabra + "\\b";
                reservada = "Sí";

            } else if (palabra.matches("-?[0-9]{1,10}")) {
                patron = "-?[0-9]{1,10}";

            } else if (palabra.matches("-?[0-9]{1,10}\\.[0-9]{1,8}")) {
                patron = "-?[0-9]{1,10}\\.[0-9]{1,8}";

            } else if (palabra.matches("\"(?:[^\"\\\\]|\\\\.)*\"")) {
                patron = "\"(?:[^\"\\\\]|\\\\.)*\"";

            } else if (palabra.matches("[a-z][a-zA-Z0-9_]*")) {
                patron = "[a-z][a-zA-Z0-9_]*";
            }

            modeloTabla.addRow(new Object[]{
                token,
                lexema,
                patron,
                reservada
            });
        }
    }

    }//GEN-LAST:event_btnAnalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.TextArea txtEntrada;
    private java.awt.TextArea txtSalida;
    // End of variables declaration//GEN-END:variables
}
